package minicraft.util;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

/**
 * Procedurally generates 3D OBJ models for custom entities.
 */
public class MeshGenerator {

    private static class Vertex {
        float x, y, z;
        Vertex(float x, float y, float z) { this.x = x; this.y = y; this.z = z; }
    }

    private static class Face {
        int[] vIndices;
        Face(int v1, int v2, int v3, int v4) { this.vIndices = new int[]{v1, v2, v3, v4}; }
    }

    private final List<Vertex> vertices = new ArrayList<>();
    private final List<Face> faces = new ArrayList<>();

    public void addBox(float x, float y, float z, float w, float h, float d) {
        int start = vertices.size() + 1;
        float x1 = x - w/2, x2 = x + w/2;
        float y1 = y,       y2 = y + h;
        float z1 = z - d/2, z2 = z + d/2;

        // 8 Vertices
        vertices.add(new Vertex(x1, y1, z1)); // 0
        vertices.add(new Vertex(x2, y1, z1)); // 1
        vertices.add(new Vertex(x2, y2, z1)); // 2
        vertices.add(new Vertex(x1, y2, z1)); // 3
        vertices.add(new Vertex(x1, y1, z2)); // 4
        vertices.add(new Vertex(x2, y1, z2)); // 5
        vertices.add(new Vertex(x2, y2, z2)); // 6
        vertices.add(new Vertex(x1, y2, z2)); // 7

        // 6 Faces (winding order)
        faces.add(new Face(start+0, start+1, start+2, start+3)); // Front
        faces.add(new Face(start+5, start+4, start+7, start+6)); // Back
        faces.add(new Face(start+4, start+0, start+3, start+7)); // Left
        faces.add(new Face(start+1, start+5, start+6, start+2)); // Right
        faces.add(new Face(start+3, start+2, start+6, start+7)); // Top
        faces.add(new Face(start+4, start+5, start+1, start+0)); // Bottom
    }

    public void export(String path) {
        try (PrintWriter out = new PrintWriter(new FileWriter(path))) {
            out.println("# Procedural Mesh Generated by MeshGenerator");
            for (Vertex v : vertices) {
                out.printf("v %.4f %.4f %.4f\n", v.x, v.y, v.z);
            }
            out.println("vt 0 0"); // Single dummy UV
            for (Face f : faces) {
                out.printf("f %d/1 %d/1 %d/1 %d/1\n", f.vIndices[0], f.vIndices[1], f.vIndices[2], f.vIndices[3]);
            }
            System.out.println("Successfully exported mesh to: " + path);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        // --- ARBORIUS ---
        MeshGenerator arb = new MeshGenerator();
        arb.addBox(0, 0.5f, 0, 1.5f, 1.2f, 2.2f); // Torso
        arb.addBox(0, 1.5f, -1.2f, 0.9f, 0.8f, 0.8f); // Head
        arb.addBox(-0.5f, 0, -0.8f, 0.4f, 0.6f, 0.4f); // Legs
        arb.addBox( 0.5f, 0, -0.8f, 0.4f, 0.6f, 0.4f);
        arb.addBox(-0.5f, 0,  0.8f, 0.4f, 0.6f, 0.4f);
        arb.addBox( 0.5f, 0,  0.8f, 0.4f, 0.6f, 0.4f);
        arb.addBox(-0.3f, 2.2f, -1.2f, 0.15f, 0.8f, 0.15f); // Horns
        arb.addBox( 0.3f, 2.2f, -1.2f, 0.15f, 0.8f, 0.15f);
        arb.export("src/main/resources/models/arborius.obj");

        // --- DRAGON ---
        MeshGenerator dra = new MeshGenerator();
        dra.addBox(0, 1.0f, 0, 1.5f, 1.0f, 3.5f); // Body
        dra.addBox(0, 1.5f, -2.5f, 0.6f, 0.6f, 1.5f); // Neck
        dra.addBox(0, 1.8f, -3.5f, 1.0f, 0.8f, 1.0f); // Head
        dra.addBox(0, 0.8f, 2.5f, 0.5f, 0.5f, 2.0f); // Tail
        dra.addBox(-2.5f, 1.5f, 0, 4.0f, 0.1f, 2.0f); // Left Wing
        dra.addBox( 2.5f, 1.5f, 0, 4.0f, 0.1f, 2.0f); // Right Wing
        dra.export("src/main/resources/models/dragon.obj");
    }
}
